In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt
import ipyparallel as ipp
%matplotlib inline

In [3]:
c = ipp.Client()

In [5]:
c.ids

[0, 1, 2, 3]

In [8]:
c[1:3].apply_sync(lambda: "Hola clase de MCA")

['Hola clase de MCA', 'Hola clase de MCA']

In [13]:
c[:].map_sync(lambda x,y,z: x+y+z, range(10), range(10), range(10))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [29]:
x = 2**25
np.arange(int(x**0.5)+1)

array([   0,    1,    2, ..., 5790, 5791, 5792])

In [40]:
#%%timeit
def PrimeQA (x):
    import numpy as np
    return all(x % i for i in np.arange(int(x**0.5)+1)[2:]) 

In [32]:
PrimeQ = lambda x: all(x % i != 0 for i in np.arange(int(x**0.5)+1)[2:]) and x>1

In [38]:
PrimeQ0(2**7)

False

In [44]:
c[0].apply_sync(PrimeQ0, 2**7)

False

In [45]:
c[:].apply_sync(PrimeQ0, 2**7)

[False, False, False, False]

In [6]:
dview = c[:]

In [53]:
2**np.arange(13)

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024,
       2048, 4096])

In [55]:
%timeit dview.map_sync(PrimeQA,2**np.arange(25))

10 loops, best of 3: 36 ms per loop


In [56]:
%%timeit
for i in 2**np.arange(25):
    x % i

The slowest run took 6.65 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 10.4 µs per loop


In [33]:
def PrimeQB (x):
    import numpy as np
    return np.all(np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]]))

In [67]:
%timeit dview.map_sync(PrimeQB,2**np.arange(25))

10 loops, best of 3: 37.6 ms per loop


In [69]:
%timeit np.mod(19,12)

The slowest run took 21.19 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.23 µs per loop


In [71]:
%timeit 19 % 12

100000000 loops, best of 3: 15.4 ns per loop


In [72]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
np.mod(np.arange(24),12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [75]:
np.array([hora % 12 for hora in np.arange(24)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [69]:
def PrimeQC (x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x,lista)
    return np.all(residuos)

In [81]:
% timeit dview.map_sync(PrimeQB,2**np.arange(25))

10 loops, best of 3: 36.4 ms per loop


In [10]:
%timeit dview.map_sync(PrimeQC,2**np.arange(25))

10 loops, best of 3: 33.7 ms per loop


In [82]:
lista = dview.map_sync(PrimeQC,-1+2**np.arange(25))
for i in range (25)[2:]:
    if(lista[i]==True):
        print i

2
3
5
7
13
17
19


In [85]:
List = dview.map_sync(PrimeQA, 2**np.arange(25)-1)
for i in range(25)[2:]:
    if List[i]==True: 
        print i

2
3
5
7
13
17
19


In [125]:
%timeit PrimeQC(2**50-1)


1 loop, best of 3: 557 ms per loop


In [105]:
for i in range(25)[2:]:
    print dview.apply_sync(PrimeQC,i)
    

[True, True, True, True]
[True, True, True, True]
[False, False, False, False]
[True, True, True, True]
[False, False, False, False]
[True, True, True, True]
[False, False, False, False]
[False, False, False, False]
[False, False, False, False]
[True, True, True, True]
[False, False, False, False]
[True, True, True, True]
[False, False, False, False]
[False, False, False, False]
[False, False, False, False]
[True, True, True, True]
[False, False, False, False]
[True, True, True, True]
[False, False, False, False]
[False, False, False, False]
[False, False, False, False]
[True, True, True, True]
[False, False, False, False]
